version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_delivery_db
    restart: always
    environment:
      POSTGRES_DB: deliveryTrujillo
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-service:
    build:
      context: .
    container_name: delivery_api_service
    ports:
      - "8080:8080"
    environment:
      # âœ… Estas variables SOBRESCRIBEN el application.properties
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/deliveryTrujillo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data: